baseURL = "https://oolavil.ai"
languageCode = "en-us"
title = "Jaakko Home"
theme = "showcase"

[params]
  author = "Jaakko Laiho"
  description = "Minimal static one-pager landing page showcasing my work"
  message = ""
  hideAutoMenu = false

[social]
  linkedin = "https://www.linkedin.com/in/jaakkolaiho/"